### ISSUE TITLE
Management command for cleaning up old data

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#349]
For example, removing old quizzes and questions. Just need to be cautious about how much is removed, since users may still have and be using quizzes on their phones, even though not currently linked to an active course

**Comment by jjoseba** [comment]
Rule to find objects to remove:
* find all the old quizzes: quizzes which digest is not associated with any present activity
* from these ones, keep the ones that have some `QuizAttempt` received
* remove every object linked with this quiz: questions, responses and props

Is there any additional rule I should have in mind to exclude some more quizzes from deletion? With this approach, in my last production DB dump there are 1278 out of 2425 to remove.
Are there any other objects besides the Quizzes that need some kind of clean up?
