### ISSUE TITLE
[Enhancement] - Progressively change the code to be PEP8 and Flake8 compliant

### ISSUE THREAD

**Issue by studiosi** [DigitalCampus/django-oppia#476]
I think it would be great if the code would be PEP8 compliant.

In case that you don't know, the [PEP8](https://www.python.org/dev/peps/pep-0008/) is an official "style guide" from the Python team for Python code. PyCharm helps a lot with this, but I know it is a pain to go through all the files in the project doing small changes here and there. I just leave this idea for the future, especially if there is going to be a project-wide refactor. What do you think?

**Comment by alexlittle** [comment]
I just had a go with the pep8ify tool (http://pep8ify.com/) and applied on the oppia/gamification directory in the pep8ify branch (https://github.com/DigitalCampus/django-oppia/tree/pep8ify)

Seems that tool would make it quite easy to update all the code...

**Comment by studiosi** [comment]
TBH most of the rules are easily mechanizable: one blank line between functions, spaces instead of tabs and so on... so I believe that these can be automatically changed. If we had a good test bench, we could be doing a whole project pep8ify and check automatically if something got broken.

**Comment by alexlittle** [comment]
Can also use pycodestyle (http://pycodestyle.pycqa.org/en/latest/index.html) to help with this

**Comment by alexlittle** [comment]
Remaining issues for this (with the exception of long line issues) are:

```
./oppia/models/main.py:54:9: E722 do not use bare 'except'
./oppia/models/main.py:187:9: E722 do not use bare 'except'
./oppia/models/main.py:236:9: E722 do not use bare 'except'
./oppia/models/main.py:248:9: E722 do not use bare 'except'
./oppia/models/main.py:269:13: E722 do not use bare 'except'
./oppia/models/main.py:414:9: E722 do not use bare 'except'
./oppia/models/main.py:426:9: E722 do not use bare 'except'
./quiz/api/serializers.py:54:21: E722 do not use bare 'except'
./quiz/api/serializers.py:69:17: E722 do not use bare 'except'
./helpers/templatetags/display_functions.py:44:5: E722 do not use bare 'except'
./helpers/templatetags/query_string.py:61:9: E722 do not use bare 'except'
./profile/views.py:497:13: E722 do not use bare 'except'
./api/resources.py:312:9: E722 do not use bare 'except'
./api/resources.py:599:9: E722 do not use bare 'except'
./viz/management/commands/ip2location.py:41:5: E722 do not use bare 'except'

./oppiamobile/settings.py:125:1: E731 do not assign a lambda expression, use a def
```

**Comment by studiosi** [comment]
The bare except can be changed to a except(Exception) I believe that catches all the exceptions

**Comment by alexlittle** [comment]
Thanks! I found a lot of these 'bare' excepts were around JSON parsing, so I was able to put in specific json encoding exceptions

**Comment by studiosi** [comment]
That's even better, it is usually not a good idea in general to do a catch-em-all exception handler...

**Comment by studiosi** [comment]
Getting rid of pokemon exceptions is always good :dancer:

**Comment by alexlittle** [comment]
I updated this to include Flake8 too - from running this it picks up a lot of additional issues than pycodestyle does on it's own, eg. unused imports etc - see this file for the current list of Flake8 lint warnings
[flake8.txt](https://github.com/DigitalCampus/django-oppia/files/3890703/flake8.txt)

**Comment by alexlittle** [comment]
transferred to OPPIA-48
