### ISSUE TITLE
MIDDLEWARE_CLASSES deprecation during installation 

### ISSUE THREAD

**Issue by studiosi** [DigitalCampus/django-oppia#477]
As we are using version 1.11, I think that a discussion about the convenience to change the MIDDLEWARE_CLASSES setting to just MIDDLEWARE would be great. I think that there can be some impact (it may require some code changes, I don't know yet all the implications) but MIDDLEWARE_CLASSES is deprecated since version 1.10.

During my installation, I created the minimal Django project through the command line

`django-admin startproject`

And it does not create the MIDDLEWARE_CLASSES (of course, because it is deprecated). When I finished the configuration, after hooking up the database and the rest of the settings, I just found that local_settings_*.py assume that said key exists in the settings map and it throws an error when doing the database creation procedure. That forced me to add this to the settings.py of the Django app:

`MIDDLEWARE_CLASSES = [] `

And I don't know if it is the best solution or even good at all.

**Comment by studiosi** [comment]
#468 is a related issue

**Comment by studiosi** [comment]
#468 Is a related issue

**Comment by alexlittle** [comment]
Thanks - yes, there are still quite a few things to do for us to keep up with the django deprecation in various versions.
For info, we keep to using the django LTS versions, so it's fairly recently that we moved from 1.8 LTS to 1.11 LTS - support for another 4+ years (so gives us some time - for these other issues in #468 at least!)

**Comment by studiosi** [comment]
Yes, this impacts the installation process, that is why I created a separate issue.

**Comment by alexlittle** [comment]
Should now be fixed in v0.11.0
