### ISSUE TITLE
Search for <media> element can fail when importing course

### ISSUE THREAD

**Issue by studiosi** [DigitalCampus/django-oppia#478]
When uploading a course, the upload fails if the XML does not contain a media element and the first child has less than 10 child elements. The problematic piece of code is the following, on  `uploader.py`

```
    for i in range(1,10):
        if xml_doc.firstChild.childNodes[i].nodeName == 'media':
            media_element = xml_doc.firstChild.childNodes[i]
            break
```

This assumes that `xml_doc.firstChild.childNodes` has a specific minimum number of elements, which may not be the case and can fail when accessing the element. The proposed solution contemplates using a list comprehension and then checking the length of the resulting list, in the following fashion:

```
    media_element_list = [node for node in xml_doc.firstChild.childNodes if node.nodeName == 'media']
    media_element = None
    if len(media_element_list) > 0:
           media_element = media_element_list[0]
```

Then the import of the media contents will only happen if `media_element is not None`

**Comment by studiosi** [comment]
Pull request under discussion: #479

**Comment by studiosi** [comment]
@alexlittle tell me if you have tested this more thoroughly and I will do a new PR to the other branch with the same changeset. Otherwise, I will test it when finishing my setup.

**Comment by alexlittle** [comment]
Yes, for sure, will have a better test of this in the next days - esp with courses that have the media element
