### ISSUE TITLE
Investigate JSON Schema for validating quiz json objects

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#484]
Currently we don't have a way to really validate the json quiz objects - they can be validated as json, but not as json objects with a specific/defined structure. So I looked for JSON equivalents for xsd for xml, and found this: http://json-schema.org/ and looks like it could do that.
I'm mainly thinking about the testing process, so we have a way to properly validate/test generated quiz output (rather than something that would be used all the time on quiz creation)

**Comment by alexlittle** [comment]
Just for reference (from David): https://spacetelescope.github.io/understanding-json-schema/

**Comment by studiosi** [comment]
Added tentative JSON Schema for the quiz on #485

**Comment by alexlittle** [comment]
transferred to OPPIA-47
