### ISSUE TITLE
Refactor migrations

### ISSUE THREAD

**Issue by jjoseba** [DigitalCampus/django-oppia#506]
Right now most of the model migrations have the default name (e.g. `00015_auto_201704151....`).
To make them more understandeable, do the following:
* Rename the files to more descriptive ones (keep track of the old ones to let Django know that the migration is applied using the `replaces` argument)
* Squash some redudant migrations to a single one, to reduce the number of them and make them clearer: https://docs.djangoproject.com/en/2.0/topics/migrations/#squashing-migrations

**Comment by alexlittle** [comment]
transferred to OPPIA-39
