### ISSUE TITLE
add_course_tags uses the request object which is not declared

### ISSUE THREAD

**Issue by studiosi** [DigitalCampus/django-oppia#511]
In this [piece of code](https://github.com/DigitalCampus/django-oppia/blob/a6ee93f723ff08dd3a2fbac68a7f3052e4caf52f/oppia/views.py#L279) (method declared on views.py line 279), the request object is used but not declared and causes an error when uploading a course with tags. Possible regression caused by a refactor?

**Comment by jjoseba** [comment]
yes... it was added in this refactor commit to reduce complexity: https://github.com/DigitalCampus/django-oppia/commit/508303fe29d0b0a963c5d8afb745ae74382639fc#diff-e701d7a51fe711d872b30af10a308b51

**Comment by studiosi** [comment]
Solved on pull request #509
