### ISSUE TITLE
Remove GCM push/device admin functionality

### ISSUE THREAD

**Issue by jjoseba** [DigitalCampus/django-oppia#512]
As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM functionalities to Firebase Cloud Messaging (FCM), which inherits the GCM infrastructure, and has a better library: https://github.com/xtrinch/fcm-django

**Comment by alexlittle** [comment]
For now we can just remove the GCM/device admin functionality - no need to replace it yet - until there is clear need for it - have edited the title accordingly
