### ISSUE TITLE
Remove development_server setting and use debug instead

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#525]
Since Django already has the debug setting, we can just use this instead of a separate on to indicate it's a dev server

**Comment by RAJKUMAR18** [comment]
Hi I would like to contribute in this project.

**Comment by alexlittle** [comment]
Hi Rajkumar, thanks for your interest in contributing. Probably the best way to get started would be to clone the code and install  the Oppia server on your local machine (the main docs are here: https://oppiamobile.readthedocs.io/en/0.11.0/), then use the 0.11.0 branch for working on as this is the next release branch. Then please feel free to send us any pull requests :-) Thanks again and if you need extra help etc we have forum on Google Groups: https://groups.google.com/forum/#!forum/oppiamobile. Cheers, Alex

**Comment by RAJKUMAR18** [comment]
Thank you Alex I will start by setting up the local environment
