### ISSUE TITLE
Move some other settings from settings.py/settings_secret.py to SettingProperties

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#567]
as with #565  - will make it easier for admins to make changes without redeploying code.

Settings that could be moved:
OPPIA_SHOW_GRAVATARS
OPPIA_POINTS_ENABLED
OPPIA_BADGES_ENABLED

BADGE_AWARDING_METHOD
OPPIA_GOOGLE_ANALYTICS_ENABLED
OPPIA_ANDROID_PACKAGEID
OPPIA_ANDROID_ON_GOOGLE_PLAY

**Comment by jatinAroraGit** [comment]
Hey there, I would like to work on this.
To be clear, I have to add new file to the migrations folder with the setting name such as 0005_show_gravatars and replicate the code in the other files in migration folder ?

**Comment by jatinAroraGit** [comment]
Hey @alexlittle , Any tips on how to run any automated test or how to check if what I did is not breaking anything.  I am very new to python,
Thanks.

**Comment by alexlittle** [comment]
Hi, sure, the automated tests ought to be straightforward to run, see: https://oppiamobile.readthedocs.io/en/latest/technical/testing/server.html
Note that at the moment there is one test that is failing - results in error saying that 3 != 1  (or vice versa), so if you get this error don't worry about it!
Thanks,
Alex
