### ISSUE TITLE
Make email and phone no optional on registration

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#593]
Many users do not have email addresses, and the more we can do to make the registration easier the better

**Comment by jjoseba** [comment]
To make the functionality more complete, instead of just making the fields optional, make them configurable via global app settings, and use them in the form `__init__()` method

**Comment by alexlittle** [comment]
We'll need to be vary careful with implementing this one, since there is a dependency on the required fields the server defines. So the server will need to be updated first

**Comment by jjoseba** [comment]
Oh, yes, this issue is about how to implement it server side, right? Now that I think of it, the best would be that the server exposed somehow which fields are mandatory, and then the app can reflect it in its registration form. For example, in the `/server` API endpoint
