### ISSUE TITLE
Add management command to process old wrong media trackers

### ISSUE THREAD

**Issue by jjoseba** [DigitalCampus/django-oppia#595]
Related to https://github.com/DigitalCampus/django-oppia/issues/579
As some tracker logs for media viewed were being submitted using the activity that contained them instead of the actual media digest, a management command is needed that processes previous tracker logs and award the corresponding points. This will probably need that a new field is added in the points table, to track which tracker log each point comes from.

**Comment by alexlittle** [comment]
transferred to OPPIA-29
