### ISSUE TITLE
Add documentation for how to run the app tests

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#599]
I'm still not getting the tests to pass in my android studio, but it might be to do with how I have Studio configured, or I'm not running the tests in the correct way.

**Comment by jbc25** [comment]
This issue belongs to this repository or the oppia-mobile-android one?

**Comment by alexlittle** [comment]
We've always kept the documentation inssues/updates in with the server repo here, since the docs are all here

**Comment by jbc25** [comment]
OK.

**Comment by alexlittle** [comment]
There is already a page here: https://oppiamobile.readthedocs.io/en/0.11.1/technical/testing/app.html - but this looks very complicated for a new user, as I think it includes info on how to create new tests too. So better the separate these out, so there's a simple page for devs just to run the tests, and then another page to explain how to add more (plus I think some of the specifics, ie version nos in the gradle, might not be correct anymore)

**Comment by alexlittle** [comment]
I split this out a little, to separate the info about just running the tests vs adding new ones, but I think the running tests part could be made even simpler. I think it would be good to have a very quickstart to just run all the tests (eg if someone has just set up the code on their machine)
