### ISSUE TITLE
Remove signup_callback function

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#605]
It basically doesn't do anything now, see: https://sonarcloud.io/project/issues?id=django_oppia&open=AWmaBEIa5QE9aC-CyjZm&resolved=false&types=CODE_SMELL and https://github.com/DigitalCampus/django-oppia/blob/0.11.1/oppia/signals.py

**Comment by PiyushSaravagi** [comment]
Hey Alex, I've never contributed to open-source projects. Would love to start here. Is this issue still open?

**Comment by alexlittle** [comment]
Hi - that would be great, and yes this issue is still open. It might be best to make the change on the 0.12.0 branch of the server, as we'll be releasing that soon, but no problem if you'd prefer to make the change on the current master branch. Just let us know if you get stuck anywhere with this... also we have our community forum site at: https://community.oppia-mobile.org/

**Comment by PiyushSaravagi** [comment]
Awesome! Will get this done and keep you updated. Thanks a lot.
