### ISSUE TITLE
Initial version of DHIS2 export

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#663]
see: https://community.oppia-mobile.org/t/dhis2-integration/63

**Comment by mridullpandey** [comment]
hey i am new here may i?

**Comment by alexlittle** [comment]
Hi @mridullpandey, thanks for your interest in contributing, and yes please feel free to have a go at this, although this particular issue might be quite a bit of work, esp for someone new to the code base.
I started a branch to work on this (see: https://github.com/DigitalCampus/django-oppia/tree/issue-663-dhis2-integration) so would be best to work on a clone of this branch. I put in a folder /integrations/dhis2/ for the code for this area of development.

Thanks again!
Alex

**Comment by alexlittle** [comment]
add some initial tests for this and the xapi integration (esp. the staff only access tests
