### ISSUE TITLE
Broken Link on CONTRIBUTING.MD

### ISSUE THREAD

**Issue by studiosi** [DigitalCampus/django-oppia#679]
This link goes to a non-existing page on the ReadTheDocs

https://oppiamobile.readthedocs.io/en/latest/dev/getting-started.html#other-ways-to-contribute

any suggestions?

**Comment by alexlittle** [comment]
Thanks for letting us know David! it's fixed now, the link should've been https://oppiamobile.readthedocs.io/en/latest/technical/dev/contribute.html
