### ISSUE TITLE
Quiz API... mainly deprecated?

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#712]
Most of the quiz api endpoints are now redundant ... since all the quiz processing takes place when the course is uploaded (not via the api from the moodle block). So a lot of this can be removed (@jjoseba - can you confirm?) - pretty much all except the QuizAttempt endpoints can be removed I think?

Since there aren't any tests either for most of this, it would make sense to remove unused and untested code.

I'll mark these functions as deprecated initially, so then we can remove these parts of the code in a future release.

**Comment by jjoseba** [comment]
From the app, the only endpoint of the quiz api called is the `/quizattempt/`.
From the Moodle block, they are used if the export method is set to local (this is the case only if there is a proper Oppia server configured that has a version below 0.9.8). I think the current scenario is that there is no mantained server and export block that are so out of date, so it can be removed.

**Comment by alexlittle** [comment]
Thanks for confirming @jjoseba  - I thought I was about right, but did want some confirmation!

Server v0.9.8 is almost 3 years old now (see: https://oppiamobile.readthedocs.io/en/latest/technical/releases/server/changelog_server_v0.9.html#v0-9-8-released-5-jan-2017) and we removed the check in the block for min version of the server, since everyone should now be using a more up to date version.

If anyone happens to be using an old version of Oppia server, and the block, then everything will keep working as-was, but certainly any implementations that are actively being maintained should no longer be using the old way of creating the quizzes via the api from the block.

**Comment by alexlittle** [comment]
Actually I think it would be good to just remove this code now, there's no point keeping unused/deprecated code...
