### ISSUE TITLE
Quiz language dictionaries not being saved correctly

### ISSUE THREAD

**Issue by jjoseba** [DigitalCampus/django-oppia#713]
It seems that quiz (quiz titles, question types, etc) languages dictionaries are being saved as python dicts instead of JSON, so for example, instead of having:

```
{"en": "Quiz"}
```
they are saved as:
```
{u'en': u'Quiz'}
```
It will probably need a migration to revert the data that is currently incorrect.

**Comment by alexlittle** [comment]
Thanks for spotting this @jjoseba !
As well as a migration to update the data in the db, would it also need to regenerate the course zip files with the correct titles? Or do you think this is something that can be left out for now?
